### ISSUE TITLE
Glot Table/Glot results error

### ISSUE THREAD

**Issue by panch13114** [go-smart/glot#1]
I get the following error when I run glot
Traceback (most recent call last):
  File "/home/pweir/.local/lib/python3.4/site-packages/glot-0.1.6-py3.4.egg/glot/connector.py", line 123, in execute_call
    result = yield from self.call(self.make_call(suffix), *args)
  File "/usr/lib/python3.4/asyncio/futures.py", line 385, in **iter**
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 288, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 274, in result
    raise self._exception
autobahn.wamp.exception.ApplicationError: ApplicationError(error=<wamp.error.no_such_procedure>, args=['no callee registered for procedure <com.gosmartsimulation.request_diagnostic>'], kwargs={}, enc_algo=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pweir/.local/lib/python3.4/site-packages/glot-0.1.6-py3.4.egg/glot/connector.py", line 87, in onJoin
    self.result = yield from self._action(self._actor, **self._kwargs)
  File "/home/pweir/.local/lib/python3.4/site-packages/glot-0.1.6-py3.4.egg/EGG-INFO/scripts/glot", line 116, in results
  File "/home/pweir/.local/lib/python3.4/site-packages/glot-0.1.6-py3.4.egg/glot/actions.py", line 211, in results
    transfer_interface
  File "/home/pweir/.local/lib/python3.4/site-packages/glot-0.1.6-py3.4.egg/glot/actions.py", line 330, in diagnostic
    if len(files) < 1:
TypeError: object of type 'NoneType' has no len()
2016-07-19T10:44:26 Task exception was never retrieved
future: <Task finished coro=<onJoin() done, defined at /home/pweir/.local/lib/python3.4/site-packages/glot-0.1.6-py3.4.egg/glot/connector.py:81> exception=TypeError("object of type 'NoneType' has no len()",)>

**Comment by panch13114** [comment]
Solved it by restarting the server side

**Comment by philtweir** [comment]
Hmm. OK - will check it out.
